&nbsp;  

### **Conferences**


---

*Oral presentations*

  - **[6-11 August 2022]** Joint Statistical Meeting 2022, *Washingthon DC, USA*

  - **[2-3 August 2022]** CHASC/RISE-ASTROSTAT Workshop 2022, *Cambridge, Massachusetts, USA* [(link)](https://hea-www.harvard.edu/AstroStat/CHASC_2122/workshop.html#description)

  - **[21-25 June 2021]** 50th Meeting of the Italian Statistical Society (SIS2021), *online*

  - **[14-18 Dec. 2020]** The European Bioconductor Meeting, *online*

  - **[14-18 Dec. 2020]** The European Bioconductor Meeting, *online*
  
  - **[17-20 June 2020]** The European R Users Meeting, *online*
  
  - **[14-16 Dec. 2019]** 12th International Conference of the ERCIM WG on Computational and
Methodological Statistics, *London, UK* (**invited**)

  - **[22-26 July 2019]** 32nd European Meeting of Statisticians, *Palermo, Italy* (**invited**)
  
  - **[8-12 July 2019]** 34th International Workshop on Statistical Modelling, *Guimarães, Portugal*
  
  - **[24-28 June 2019]** 12th International Conference on Bayesian Nonparametrics, *Oxford, UK*
  
  - **[14-16 Dec. 2018]** 11th International Conference of the ERCIM WG on Computational and
Methodological Statistics, *Pisa, Italy* (**invited**)

  - **[15-20 July 2018]** 33rd International Workshop on Statistical Modelling, *Bristol, UK*
  
  - **[28-30 June 2017]** Statistics and Data Sciences: New Challenges, New Generations.
Conference of the Italian Statistical Society, *Florence, Italy*

---

*Poster presentations*

  - **[26 June - 1 July 2022]** Conference of the International Society of Bayesian Analysis, *Montreal, Canada*
  
  - **[7-10 June 2021]** Statistical Challenges in Modern Astronomy VII, *online*
  
  - **[2-4 June 2021]** Mixtures, Hidden Markov Models, Clustering 2021, *online*

  - **[3-6 Sept. 2018]** Conference of the Royal Statistical Society, *Cardiff, UK*
  
  - **[24-29 June 2018]** Conference of the International Society of Bayesian Analysis, *Edinburgh, UK*
  
  - **[8 Sept. 2017]** `Astro@Stat 2017`: Sino-Italian Workshop on Astrostatistics, *Padova, Italy*
