
### **Publications**


---

*In journals*

  - **Sottosanti, A.**, Denti, F., Galimberti, S., Risso, D., and Capitoli, G. (2024) Spatially informed nonnegative matrix trifactorization for coclustering mass spectrometry data. *Biometrical Journal*. **In press**

  - Montin, A., Brazzale, A. R., Menardi, G., and **Sottosanti, A.** (2023) Locating $\gamma$-ray sources on the celestial sphere via modal clustering. *Statistical Methods & Applications*. [(link)](https://link.springer.com/article/10.1007/s10260-023-00726-w?utm_source=rct_congratemailt&utm_medium=email&utm_campaign=oa_20231005&utm_content=10.1007/s10260-023-00726-w)

  - Ianniello, A., **Sottosanti, A.**, Borriello, G., and Vincenti, M. (2023) Perception of Quality of Life and Fatigue in Multiple Sclerosis Patients Treated with High-Dose Vitamin D. *Clinical and Translational Neuroscience* 7(2):12-27. [(link)](https://www.mdpi.com/2514-183X/7/2/12)


  - Righelli, D., **Sottosanti, A.**, and Risso, D. (2023) Designing spatial transcriptomic experiments. *Nature Methods* 20(3):355-356. [(link)](https://www.nature.com/articles/s41592-023-01801-6)

  - **Sottosanti, A.**, and Risso, D. (2023) Co-clustering of Spatially Resolved Transcriptomic Data. *The Annals of Applied Statistics* 17(2):1444-1468. [(link)](https://projecteuclid.org/journals/annals-of-applied-statistics/volume-17/issue-2/Co-clustering-of-spatially-resolved-transcriptomic-data/10.1214/22-AOAS1677.short?tab=ArticleLink)
  
  - **Sottosanti, A.**, Risso, D., and Castiglione, C. (2022) Contributed discussion: "Bayesian Nonstationary and Nonparametric Covariance Estimation for Large Spatial Data" by B. Kidd and M. Katzfuss. *Bayesian Analysis* 17(1):337-339. [(link)](https://projecteuclid.org/journals/bayesian-analysis/volume-17/issue-1/Bayesian-Nonstationary-and-Nonparametric-Covariance-Estimation-for-Large-Spatial-Data/10.1214/21-BA1273.full)

  - Hayden, E., Airoldi, C., Scotti, L., Bellan, M., **Sottosanti, A.**, Bergamasco, P., Salamina, L., Capponi, A., Sainaghi, P.P., and Pirisi, M. (2021) Modelling hospital bed necessity for COVID-19 patients during the decline phase of the epidemic trajectory. *Minerva Respiratory Medicine* 60(2):29-35. [(link)](https://www.minervamedica.it/en/journals/minerva-respiratory-medicine/article.php?cod=R16Y2021N02A0029)
  
  - Costantin, D., **Sottosanti, A.**, Brazzale, A. R., Bastieri, D., Fan, J. (2022) Bayesian Mixture Modeling of the High-Energy Photon Counts collected by the Fermi Large Area Telescope. *Statistical Modelling* 22(3):175-198. [(link)](https://journals.sagepub.com/doi/pdf/10.1177/1471082X20947222)

---

*In volumes*

  - **Sottosanti, A.**, Costantin, D., Bastieri, D., and Brazzale, A. R. (2019). Discovering and Locating
High-Energy Extra-Galactic Sources by Bayesian Mixture Modelling. *New Statistical Developments
in Data Science* (A. Petrucci, F. Racioppi and R. Verde Eds.), Springer Proceedings in Mathematics
& Statistics, 288, 135-148. [(link)](https://link.springer.com/chapter/10.1007/978-3-030-21158-5_11)

  - Caponera, A., Denti, F., Rigon, T., **Sottosanti, A.**, and Gelfand, A. (2018). Hierarchical Spatio-
Temporal Modeling of Resting State fMRI Data. *Studies in Neural Data Science* (A. Canale, D.
Durante, L. Paci and B. Scarpa Eds.), Springer Proceedings in Mathematics & Statistics, 257,
111-130. [(link)](https://link.springer.com/chapter/10.1007/978-3-030-00039-4_7)

---

*In proceedings*

  - **Sottosanti, A.** and Risso, D. (2021) Co-clustering Models for Spatial Transciptomics: Analysis of a Human Brain Tissue Sample. Proceedings of the 50th Scientific meeting of the Italian Statistical Society.

  - **Sottosanti, A.**, Bernardi, M., Campos, L., Siemiginowska, A. and van Dyk, D.A. (2019) Continuous time hidden Markov models for astronomical gamma-ray light curves. Proceedings of the 34th International Workshop on Statistical Modelling (IWSM 2019), 7-12 July 2019, Guimarães
(Portugal). **Best student paper**

  - Busatto, C., **Sottosanti, A.** and Bernardi, M. (2019). Bayesian Variable Selection for High
Dimensional Logistic Regression. Smart Statistics for Smart Applications: Book of Short Papers
SIS2019, 18-21 June 2019, Milan (Italy).

  - **Sottosanti, A.**, Bernardi, M., Brazzale, A.R. (2018) Mining signals of astronomical sources
via Bayesian nonparametric mixture modelling. Proceedings of the 33rd International Workshop
on Statistical Modelling (IWSM 2018), 16-20 July, Bristol (UK). **Runner-up as best student
paper**

  - **Sottosanti, A.**, Bastieri, D., Brazzale, A.R. (2017). Bayesian Mixture Models for the Detection
of High-Energy Astronomical Sources. Statistics and Data Science: new challenges, new genera-
tions, 28-30 June 2017, Florence (Italy).

---

*Under review*

  - **Sottosanti, A.**, Belloni, P., Bovo, E., and Boccuzzo, G. (2024+) Bayesian mapping of mortality clusters. [(preprint)](https://arxiv.org/abs/2407.19135)

  - **Sottosanti, A.**, Bernardi, M., Brazzale, A. R., Geringer-Sameth, A., Stenning, D. C., Trotta,
R. and van Dyk, D. A. (2021+) Identification of high-energy astrophysical point sources via hierarchical Bayesian nonparametric clustering. [(preprint)](https://arxiv.org/abs/2104.11492)

---

&nbsp; 

### **Reviewing activity**

 - BMC-Bioinformatics
 - Bioinformatics
 - Computational Statistics
 - Environmental and Ecological Statistics
 - Nature Communications
 - Quantitative Finance and Economics.
 - Statistical Methods & Applications